import 'package:flutter_chat/network/dto/chat_dto.dart';

abstract class ChatApiService {
  /// Step 2 — POST the user message. Backend persists it on Supabase and
  /// returns the SQL generated by OpenAI (step 6).
  Future<SqlOutDto> sendMessage(MessageInDto payload);

  /// Step 8 — POST the rows produced locally by sqflite. Backend asks
  /// OpenAI to format the natural-language reply and returns it (step 11).
  Future<FinalAnswerOutDto> processSqlResults(SqlResultsInDto payload);
}
